version: '3'

services:
  hero-server:
    image: hero-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "8080:8080"
  redis:
    image: redis
    ports:
      - "6379:6379"
